<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <Verify_SponsorshipExemption>$(VerifySponsorshipExemption)</Verify_SponsorshipExemption>
        <Verify_SponsorshipExemptionUntil>$(VerifySponsorshipExemptionExpiry)</Verify_SponsorshipExemptionUntil>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="8.8.0" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
      <PackageReference Include="Microsoft.Testing.Platform" Version="2.4.1" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="NSubstitute" Version="6.2.0" />
      <PackageReference Include="StubLogger" Version="3.0.2.10" />
      <PackageReference Include="Verify.XunitV3" Version="33.0.2" />
      <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="xunit.v3" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\BlazorMerge\BlazorMerge.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="TestResults\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="TestResults\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="TestResults\**" />
    </ItemGroup>

</Project>
