name: 'Blazor Merge Action'
description: 'Combines the appsettings.json and appsettings.environment.json files into a single appsettings.json file'
inputs:
  app-environment:
    description: 'The environment to use for the appsettings file'
    required: true
  path:
    description: 'The path to the appsettings files'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/AfterLife-Guide/appsettings.merge:dummy'
  args:
    - '-e'
    - ${{ inputs.app-environment }}
    - '-p'
    - '/github/workspace${{ inputs.path }}'
branding: 
    icon: 'git-merge'
    color: 'green'
