name: Completed Feature Workflow

on:
  pull_request:
    branches: [ develop ]
    types: [closed]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-merged-issue-issues:
    if: github.event.pull_request.merged_by != '' && github.actor != 'dependabot[bot]' && startsWith(github.head_ref, 'feature/issue-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Extract Issue Number
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: echo "issue=$(echo \"$BRANCH_NAME\" | sed 's|[^0-9]||g')" >> $GITHUB_OUTPUT
        id: extract_issue
      - name: Output Issue Number
        run: echo "Issue Number- ${{ steps.extract_issue.outputs.issue }}"
      - name: Update Labels
        run: gh issue edit ${{ steps.extract_issue.outputs.issue }} --add-label "status:next release" --remove-label "status:in progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
