on:
  workflow_call:
    inputs:
      version:
        description: 'The version number to use for the build'
        required: true
        type: string
      checkout-ref:
        description: 'The commit SHA to checkout'
        required: true
        type: string
  
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Log Branch
      run: |
        echo "Branch: ${{ inputs.checkout-ref }}"
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        ref: ${{ inputs.checkout-ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d
      with:
        dotnet-version: 8.0.x
    - name: Restore
      uses: cake-build/cake-action@5167c3f6a9e15c76f009de2acdfb9488552bc0b9
      with:
        target: Restore
    - name: Build
      uses: cake-build/cake-action@5167c3f6a9e15c76f009de2acdfb9488552bc0b9
      with:
        target: Build
        arguments: |
          versionNumber: ${{inputs.version}}
    - name: Run tests
      uses: cake-build/cake-action@5167c3f6a9e15c76f009de2acdfb9488552bc0b9
      with:
        target: Test
    - name: Publish Unit Test Results
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: EnricoMi/publish-unit-test-result-action/linux@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6
      with:
        files: "**/TestResults/*.xml"